const Constants = {
    HEADER_GET_DATA: 'HEADER_GET_DATA',
    HEADER_DATA_RECIEVED: 'HEADER_DATA_RECIEVED',
    // DISCUSS_ADD_MSG: 'DISCUSS_ADD_MSG',
    // DISCUSS_ADD_SHORT_MSG: 'DISCUSS_ADD_SHORT_MSG',
    // DISCUSS_CLEAR_NEW_MSG: 'DISCUSS_CLEAR_NEW_MSG',
    // DISCUSS_CHANGE_CONS_STATUS: 'DISCUSS_CHANGE_CONS_STATUS'
};

export default Constants
